pull_request_rules:
  - name: Merge approved and green PRs with `merge when green` label
    conditions:
      - "#approved-reviews-by>=1"
      - status-success~=^test \([0-9]+\.x, ubuntu-latest\)$
      - label=merge when green
      - or:
          - base=main
          - base=v0.0.1
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
        commit_message: title+body
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success~=^test \([0-9]+\.x, ubuntu-latest\)$
      - base=main
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
        commit_message: title+body
